### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by zhouge146** [xieyezi/sku-algorithm#1]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sku-algorithm@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sku-algorithm@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dddd\AppData\Roaming\npm-cache\_logs\2020-06-24T09_37_00_120Z-debug.log

**Comment by xieyezi** [comment]
先执行了npm install ，然后执行npm run start

**Comment by zhouge146** [comment]
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sku-algorithm@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sku-algorithm@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\dddd\AppData\Roaming\npm-cache_logs\2020-06-24T09_37_00_120Z-debug.log



> 先执行了npm install ，然后执行npm run start

这些都执行了，然后刚才也从新安装了ynpm 还是无济于事

**Comment by xieyezi** [comment]
@zhouge146  你安装 “create-react-app”了吗，如果没有，就全局安装一下

**Comment by xieyezi** [comment]
如果你已经安装了，试一下下面的👇的步骤：

1、`npm install -g npm@latest ` ,可能你的npm不是最新的
2、用`rm -rf node_modules` 先删掉全部依赖
3、重新执行 `npm install`
