### ISSUE TITLE
按照readme中的方法写出来有bug

### ISSUE THREAD

**Issue by cq641876623** [xieyezi/sku-algorithm#20]
![image](https://github.com/xieyezi/sku-algorithm/assets/29827087/7484fdb1-b506-4b6e-84bd-347883dc734c)
错误结果是[ 红色，64G，8G]可以选，在糗邻接矩阵相交结果时会发生 因为红色在128G的路径中与6G和8G相连而且因为在黑色的64G属性中与8G相连 在邻接表中会出现如下情况导致bug复现，不知道后期有没有代码改进这个bug，如果是我理解错文档了，麻烦帮忙指正一下谢谢
![image](https://github.com/xieyezi/sku-algorithm/assets/29827087/99f9c9ee-0d46-491f-95b2-a912175c7b7a)

**Comment by xieyezi** [comment]
@cq641876623 通过加权的方式可以解决这个问题，再试试。

<img width="845" alt="image" src="https://github.com/xieyezi/sku-algorithm/assets/16821989/08e1c450-55e5-4c6c-9767-43f8d90d4ad6">
